### ISSUE TITLE
I got error while compiling every time (simple codes from examples)

### ISSUE THREAD

**Issue by nonameprogram** [Skriware/Skribots#2]
Arduino:1.8.10 (Windows 10), Płytka:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\User\Documents\Arduino\libraries\Skribots\src\SkriBot.cpp: In member function 'void Skribot::Configure_Connections(String)':

C:\Users\User\Documents\Arduino\libraries\Skribots\src\SkriBot.cpp:54:146: error: no matching function for call to 'StatusLED::StatusLED(const uint8_t&, const uint8_t&, const uint8_t&, const uint8_t&)'

           status = new StatusLED(EDU_SHIELD_STATUS_LED_R_PIN,EDU_SHIELD_STATUS_LED_G_PIN,EDU_SHIELD_STATUS_LED_B_PIN,EDU_SHILED_POWER_READOUT_PIN);

                                                                                                                                                  ^

In file included from C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/RGB_LED_Matrix.h:5:0,

                 from C:\Users\User\Documents\Arduino\libraries\Skribots\src\Skribot.h:13,

                 from C:\Users\User\Documents\Arduino\libraries\Skribots\src\SkriBot.cpp:1:

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:16:2: note: candidate: StatusLED::StatusLED(byte, byte, byte, byte, byte)

  StatusLED(byte R_pin,byte G_pin,byte B_pin,byte Battery_pin,byte Board_V);

  ^~~~~~~~~

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:16:2: note:   candidate expects 5 arguments, 4 provided

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:12:8: note: candidate: constexpr StatusLED::StatusLED(const StatusLED&)

  class StatusLED

        ^~~~~~~~~

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:12:8: note:   candidate expects 1 argument, 4 provided

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:12:8: note: candidate: constexpr StatusLED::StatusLED(StatusLED&&)

C:\Users\User\Documents\Arduino\libraries\Skribots\src/utilities/StatusLED.h:12:8: note:   candidate expects 1 argument, 4 provided

Znaleziono wiele bibliotek w "Skribot.h"
Wykorzystane: C:\Users\User\Documents\Arduino\libraries\Skribots
Znaleziono wiele bibliotek w "EEPROM.h"
Wykorzystane: C:\Program
Znaleziono wiele bibliotek w "Servo.h"
Wykorzystane: C:\Program
Znaleziono wiele bibliotek w "SPI.h"
Wykorzystane: C:\Program
Znaleziono wiele bibliotek w "Wire.h"
Wykorzystane: C:\Program
exit status 1
Błąd kompilacji dla płytki Arduino/Genuino Mega or Mega 2560.

Ten raport powinien zawierać więcej informacji jeśli w 
File -> Preferencje zostanie włączona opcja "Pokaż
szczegółowe informacje podczas kompilacji"

my code
```

#include <Skribot.h>
Skribot robot;
void setup() { 
    robot.AddDCRotor("LEFT");         
    robot.AddDCRotor("RIGHT");
    robot.SetSpeed(250);              
}
void loop() {    
        robot.MoveForward(2000);
        robot.FaceRight(1000); 
        robot.MoveForward(2000);    
        robot.TurnLeft(1000); 
}
```

**Comment by adzierzanowski** [comment]
Hi,

thank you for creating an issue. It should be resolved by now. Please, try updating the library.
